### ISSUE TITLE
Fix error when creating a new file permission

### ISSUE THREAD

**Issue by Kaede25** [SYP-AHIF-2023-24-25/SolarDoc#231]
For some reason the following error gets thrown every time a new file permission gets created:

```
[error] #PID<0.546.0> running Phoenix.Endpoint.SyncCodeReloadPlug (connection #PID<0.480.0>, stream id 8) terminated
Server: localhost:4000 (http)
Request: POST /phx/api/v2/files/permissions
** (exit) an exception was raised:
    ** (UndefinedFunctionError) function Repo.preload/2 is undefined (module Repo is not available)
        Repo.preload(%SolardocPhoenix.Permissions.FilePermission{__meta__: #Ecto.Schema.Metadata<:loaded, "file_permissions">, id: "894363c1-0e5b-4c23-b35e-d0e8cb491132", permission: 3, file_id: "fa9e9b1a-8139-47ed-a852-3667042cc144", file: #Ecto.Association.NotLoaded<association :file is not loaded>, user_id: "fa883013-fb41-4217-8f1b-64bcba8febc7", user: #Ecto.Association.NotLoaded<association :user is not loaded>, inserted_at: ~U[2024-11-23 14:41:42Z], updated_at: ~U[2024-11-23 14:41:42Z]}, :user)
        (solardoc_phoenix 1.0.0-dev.4) lib/solardoc_phoenix_web/v2/controllers/files/file_permission_controller.ex:84: SolardocPhoenixWeb.V2.FilePermissionController.create/2
        (solardoc_phoenix 1.0.0-dev.4) lib/solardoc_phoenix_web/v2/controllers/files/file_permission_controller.ex:1: SolardocPhoenixWeb.V2.FilePermissionController.action/2
        (solardoc_phoenix 1.0.0-dev.4) lib/solardoc_phoenix_web/v2/controllers/files/file_permission_controller.ex:1: SolardocPhoenixWeb.V2.FilePermissionController.phoenix_controller_pipeline/2
        (phoenix 1.7.10) lib/phoenix/router.ex:432: Phoenix.Router.__call__/5
        (solardoc_phoenix 1.0.0-dev.4) lib/solardoc_phoenix_web/endpoint.ex:1: SolardocPhoenixWeb.Endpoint.plug_builder_call/2
        (solardoc_phoenix 1.0.0-dev.4) deps/plug/lib/plug/debugger.ex:136: SolardocPhoenixWeb.Endpoint."call (overridable 3)"/2
        (solardoc_phoenix 1.0.0-dev.4) lib/solardoc_phoenix_web/endpoint.ex:1: SolardocPhoenixWeb.Endpoint.call/2
        (phoenix 1.7.10) lib/phoenix/endpoint/sync_code_reload_plug.ex:22: Phoenix.Endpoint.SyncCodeReloadPlug.do_call/4
        (plug_cowboy 2.7.0) lib/plug/cowboy/handler.ex:11: Plug.Cowboy.Handler.init/2
        (cowboy 2.10.0) /home/emma/SYP/SolarDoc/solardoc/phoenix-server/deps/cowboy/src/cowboy_handler.erl:37: :cowboy_handler.execute/2
        (cowboy 2.10.0) /home/emma/SYP/SolarDoc/solardoc/phoenix-server/deps/cowboy/src/cowboy_stream_h.erl:306: :cowboy_stream_h.execute/3
        (cowboy 2.10.0) /home/emma/SYP/SolarDoc/solardoc/phoenix-server/deps/cowboy/src/cowboy_stream_h.erl:295: :cowboy_stream_h.request_process/3
        (stdlib 6.1.2) proc_lib.erl:329: :proc_lib.init_p_do_apply/3
```

**Comment by Luna-Klatzer** [comment]
Fixed by #236 and will be shipped in `v1.0.0-dev.6`.
